### PR TITLE
Feat: add windows wheels

### LINKED ISSUE #24: Build wheels for Windows
We currently use [GitHub Actions](https://github.com/ada-url/ada-python/blob/7a871f4702bc69fe6cc1a03589e097843f9070c8/.github/workflows/build.yml) and `cibuildwheel` to build wheel packages for Linux and Mac. However, it should be possible to also create Windows wheels.

### PR DESCRIPTION
**Pull request by plusiv**
Aims to fix #24 .

Currently `cibuildwheel` supports windows builds.

### CODE REVIEW

**Comment by Master-Hash** [comment]
The problem is at the C/C++ library, I guess it cannot work well with msvc.

**Comment by anonrig** [comment]
> The problem is at the C/C++ library, I guess it cannot work well with msvc.

Ada supports MSVC 2019+ and used by Node.js and Cloudflare Workers at the moment. If you think there is a bug with Ada, please open an issue to the Ada repository.

**Comment by plusiv** [comment]
The real problem seems to be that the object file `ada.o` is not being generated before wheel build, I need to specify that from the `Makefile` in the `pyproject.toml` file. Unfortunately I don't have my Windows machine with me right now to make some more tests locally before pushing more changes, and I don't want to waste the actions minutes.

I'm Going to push more changes tomorrow.

**Comment by Master-Hash** [comment]
If you're occupied, I may try to fix it this evening(UTC+8). @plusiv

**Comment by plusiv** [comment]
Closed due #47.
Thanks @Master-Hash

**Pull request closed without merging**
