### PR TITLE
Feat: Add  `len` builtin function to `URLSearchParams` class 

### PR DESCRIPTION
**Pull request by plusiv**
This change aims to use the built-in function `len()` for getting the search params passed to the class `URLSearchParams`, instead of using the `size` property, `len` is a more pythonic and idiomatic way to retrieve a count of items.

## Example of usage
```python
>>> from ada_url import URLSearchParams
>>> obj = URLSearchParams('key1=value1&key2=value2&key2=value3')
>>> len(obj)
3
```

### CODE REVIEW

**Review by anonrig — APPROVED** [review]

**Comment by bbayles** [comment]
I had this in the class initially, but took it out. I think it's fine to have a `len`, but then should we also have a `__getattr__`, `__setattr__`, `__delattr__`, etc? I decided to leave the interface roughly the same as the WHATWG one and let the Python functions be friendlier.

Or would you use `__len__` without expecting attribute setting and getting to work?

**Comment by plusiv** [comment]
@bbayles thanks for your comment. 

I agree with you about keeping compatibility with the mainstream project, however, imho, adding magic methods could help to improve readability for Python developers, and make the API still being friendly. This PR does not remove the old API, but adds a more fancy way to use the Python API.

**Comment by plusiv** [comment]
@plusiv btw, the purpose of my idea is not to override the classic methods, but provide a Pythonic way to use them.

**Comment by bbayles** [comment]
Right, but do you have an idea of a limiting principle? Would you want the get/set functions as well? I'm trying to decide whether to add those too, and if not, whether length makes sense.

**Comment by plusiv** [comment]
I don't get why is this falling, Do you guys have any clue?

**Comment by bbayles** [comment]
Looks like it was an intermittent failure with one of the wheel builds.

I've still not decided whether to make this a general purpose "multidict" data structure, so I'm holding off on merging.

**Comment by bbayles** [comment]
I looked into how other libraries and treat structures with repeated keys (e.g. request headers and query parameters). There doesn't seem to be a common approach:
* CPython's `urllib.parse.parse_qs` returns a dictionary with string keys and lists of string values. You can modify with standard `dict` and `list` methods.
* CPython's `urllib.parse.parse_qsl` returns a list of key, value pairs. You can modify with standard `list` methods.
* `requests.structures.CaseInsensitiveDict` sidesteps the problem by returning comma separated lists of values (which is legal for headers; doesn't make sense for URL parameters)
* [MultiDict](https://multidict.aio-libs.org/en/stable/multidict.html#multidict.MultiDict) is reasonably popular, but it has an idiosyncratic API that doesn't seem any more or less intuitive than the one described in the WHAT WG spec.

Anyway, I'll merge in this `__len__` change on the off chance that somebody expects it to work, but I'll decline to do any further `dict`-like extensions.

Thanks!

**Pull request merged**
