### PR TITLE
Added OpenSSF Scorecard

### PR DESCRIPTION
**Pull request by UlisesGascon**

### CODE REVIEW

**Review by anonrig — APPROVED** [review]

**Comment by bbayles** [comment]
I think this is fine, if it's what the rest of the `ada` repos are doing.

**Comment by anonrig** [comment]
> I think this is fine, if it's what the rest of the `ada` repos are doing.

We follow it on `ada` and `mimesniff` repositories for now. This comes with several maintenance burdens, since you're the maintainer, I believe you should make the decision on this one @bbayles.

**Comment by bbayles** [comment]
I'll review how those repos use this action when I get back from parental leave. Thanks!

**Comment by bbayles** [comment]
I think I'm not going to take this one on. Thanks for the PR in any case!

**Pull request closed without merging**
